#ifndef MYCONSTANTS_H_INCLUDED
#define MYCONSTANTS_H_INCLUDED

//enum{QUARZ,CLK2M,CLK32M};

#define SYSCLK CLK32M

#define PLL 0

#define CLOCK_CALIBRATION 0x83



#define LED_ROT_ON		PORTA_OUTCLR = PIN4_bm
#define LED_ROT_OFF		PORTA_OUTSET = PIN4_bm
#define LED_ROT_TOGGLE	PORTA_OUTTGL = PIN4_bm
#define LED_GELB_ON		PORTA_OUTCLR = PIN5_bm
#define LED_GELB_OFF		PORTA_OUTSET = PIN5_bm
#define LED_GELB_TOGGLE	PORTA_OUTTGL = PIN5_bm
#define LED_GRUEN_ON		PORTA_OUTCLR = PIN6_bm
#define LED_GRUEN_OFF		PORTA_OUTSET = PIN6_bm
#define LED_GRUEN_TOGGLE	PORTA_OUTTGL = PIN6_bm
#define LED_BLAU_ON		PORTA_OUTCLR = PIN7_bm
#define LED_BLAU_OFF		PORTA_OUTSET = PIN7_bm
#define LED_BLAU_TOGGLE	PORTA_OUTTGL = PIN7_bm

// Debug-Pin
#define DEBUGPIN_PORT  PORTA
#define DEBUGPIN_PIN   PIN1_bm

#define DEBUGPIN_DATA			(DEBUGPIN_PORT.IN & DEBUGPIN_PIN)
#define DEBUGPIN_IS_CLEAR	bit_is_clear(DEBUGPIN_PORT,DEBUGPIN_PIN)
#define DEBUGPIN_IS_SET		bit_is_set(DEBUGPIN_PORT,DEBUGPIN_PIN)
#define GET_DEBUGPIN      (DEBUGPIN_DATA_SET==0 ? false: true)



#endif // MYCONSTANTS_H_INCLUDED
